package com.example.policlicabine.entity.enums;

public enum FormPurpose {
    GDPR_CONSENT,
    ANESTHESIA_CONSENT,
    SURGERY_CONSENT,
    GENERAL_CONSENT,
    MEDICAL_HISTORY,
    ALLERGIES,
    CURRENT_MEDICATIONS,
    SYMPTOMS_ASSESSMENT,
    PRESCRIPTION,
    TREATMENT_PLAN,
    POST_TREATMENT_NOTES,
    PATIENT_INTAKE,
    PRE_CONSULTATION_QUESTIONNAIRE
}
